[2019-06-26 23:20:25,501]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:20:25,785]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:20:26,118]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:20:26,769]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:20:27,055]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:20:27,345]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:20:27,644]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:29,774]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:30,056]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:30,345]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:30,648]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:31,168]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:31,544]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:29:31,900]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:49,244]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:49,571]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:49,852]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:50,142]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:50,471]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:50,784]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-26 23:31:51,092]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:41,825]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:43,240]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:43,951]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:44,274]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:44,561]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:44,849]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 09:44:45,587]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:33:05,468]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:33:05,487]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:33:05,489]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:33:05,490]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:33:05,491]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:34:28,149]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:34:29,510]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:34:30,817]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:34:31,192]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:34:31,489]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:56:55,426]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:56:55,465]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:58:27,177]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:58:27,179]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:59:40,691]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 10:59:40,693]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:02:57,852]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:02:57,855]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:03:32,186]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:03:33,855]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:16:32,903]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:16:33,370]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:16:34,084]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:16:34,144]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: 1000 != Decimal('29384442.36')
[2019-06-27 11:16:34,309]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:17:14,061]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:17:14,529]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:17:15,054]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:17:15,054]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14692221.18') != Decimal('29384442.36')
[2019-06-27 11:17:15,221]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:18:02,205]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:18:02,669]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:18:03,253]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:18:03,254]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14692221.18') != Decimal('14693221.18')
[2019-06-27 11:18:03,421]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:19:58,775]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:19:59,596]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:20:00,181]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:20:00,181]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:20:00,350]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:21:23,725]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:21:24,375]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:21:24,620]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:23:04,822]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:23:05,193]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:23:05,404]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:23:22,450]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:23:22,919]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:23:23,452]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:23:23,454]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:23:23,620]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:27:39,613]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:27:40,066]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:27:40,691]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:27:40,691]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:27:40,692]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:27:40,858]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:29:35,324]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:29:35,696]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:29:36,297]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:29:36,297]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:29:36,298]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:29:36,470]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:46:35,822]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:46:36,442]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:46:37,068]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:46:37,070]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:46:37,072]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:47:54,699]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:47:55,416]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:47:56,094]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:47:56,095]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:47:56,096]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:16,356]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:16,858]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:49:18,070]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:49:18,071]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:49:18,074]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:49:18,231]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:18,459]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:18,702]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:18,912]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:19,117]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:19,355]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:19,878]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:49:20,457]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:49:20,458]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 11:49:20,462]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '10000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 11:49:20,625]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:21,065]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:49:21,666]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:49:21,667]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 11:49:21,667]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 11:49:21,829]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:22,058]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:49:22,765]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:06,683]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:07,158]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:50:07,781]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:50:07,782]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:50:07,782]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:50:07,948]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:08,161]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:08,474]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:08,709]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:08,910]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:09,138]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:09,623]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:50:10,179]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:50:10,179]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 11:50:10,181]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '511000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 11:50:10,340]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:11,115]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:50:11,660]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:50:11,660]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 11:50:11,661]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 11:50:11,826]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:12,047]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:50:12,240]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:30,725]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:31,058]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:52:32,033]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:52:32,033]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:52:32,034]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:52:32,193]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:32,398]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:32,615]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:32,821]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:33,015]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:33,236]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:33,682]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:52:34,348]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:52:34,349]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 11:52:34,353]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '1012000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 11:52:34,513]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:34,919]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:52:35,500]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:52:35,500]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 11:52:35,500]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 11:52:35,660]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:35,921]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:52:36,596]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:55:10,759]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:55:11,100]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:55:11,666]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:55:11,668]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:55:11,670]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:55:11,829]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:56:28,356]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:56:28,702]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:56:29,241]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:56:29,241]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:56:29,242]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:56:29,400]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:53,435]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:53,868]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:57:54,462]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:57:54,463]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 11:57:54,463]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 11:57:54,620]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:54,898]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:55,196]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:55,485]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:55,803]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:56,115]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:56,542]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:57:57,480]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:57:57,481]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 11:57:57,483]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '1515000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 11:57:57,639]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:58,107]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 11:57:58,754]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 11:57:58,755]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 11:57:58,756]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 11:57:58,946]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:59,245]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 11:57:59,625]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:00,609]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:01,093]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:00:01,730]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:00:01,732]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 12:00:01,734]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 12:00:01,890]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:02,167]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:02,518]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:02,820]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:03,108]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:03,408]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:03,786]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:00:04,434]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:00:04,434]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 12:00:04,436]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '2016000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 12:00:04,593]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:05,321]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:00:05,823]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:00:05,824]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 12:00:05,824]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 12:00:06,003]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:06,293]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:00:06,576]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:23,754]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:24,448]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:01:25,111]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:01:25,111]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 12:01:25,112]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 12:01:25,278]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:25,600]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:25,894]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:26,178]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:26,449]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:26,733]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:27,237]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:01:27,885]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:01:27,886]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 12:01:27,889]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '2517000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 12:01:28,054]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:28,556]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:01:29,306]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:01:29,306]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 12:01:29,308]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 12:01:29,487]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:29,811]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:01:30,098]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:10,739]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:11,159]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:02:11,811]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:02:11,813]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 12:02:11,815]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 12:02:11,856]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:12,025]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:12,204]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:12,380]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:13,101]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:13,284]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:13,731]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:02:14,198]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:02:14,199]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 12:02:14,201]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '3018000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 12:02:14,245]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:14,665]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:02:15,505]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:02:15,505]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 12:02:15,506]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 12:02:15,547]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:15,777]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:15,970]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:23,392]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:23,890]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:02:24,426]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:02:24,427]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 12:02:24,427]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 12:02:24,583]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:24,877]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:25,206]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:25,536]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:25,837]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:26,143]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:26,468]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:02:27,071]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:02:27,071]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 12:02:27,072]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '3519000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 12:02:27,228]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:27,670]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 12:02:28,426]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 12:02:28,428]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 12:02:28,430]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 12:02:28,614]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:28,906]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:02:29,207]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:04,166]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:04,606]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 12:06:05,246]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 12:06:05,247]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 12:06:05,248]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 12:06:05,407]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:47,850]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:48,231]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 12:06:48,849]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 12:06:48,850]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 12:06:48,850]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 12:06:49,007]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:49,284]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:49,604]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:49,925]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:50,225]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:50,503]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:50,991]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 12:06:51,604]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 12:06:51,605]-[INFO]-log.py-python14-[日志信息]:提现金额0
[2019-06-27 12:06:51,606]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '10256021.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '取现成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '3999000.00',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '取现成功',
 'status': 1}
[2019-06-27 12:06:51,764]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:52,270]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 12:06:52,879]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 12:06:52,881]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid literal for int() with base 10: '0.01'
[2019-06-27 12:06:53,060]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:53,598]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 12:06:54,158]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 12:06:54,159]-[INFO]-log.py-python14-[日志信息]:提现金额500000
[2019-06-27 12:06:54,160]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14192221.18') != Decimal('14692221.18')
[2019-06-27 12:06:54,318]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:54,660]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:54,968]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:06:55,266]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:20:56,943]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1} != {'code': '20103', 'data': None, 'msg': '手机号不能为空', 'status': 0}
[2019-06-27 12:20:57,110]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:20:57,414]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 12:20:57,416]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:21:47,375]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 12:21:47,377]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:22:29,319]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:22:41,232]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:24:22,097]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:24:35,944]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:48:14,083]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:49:08,873]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:49:28,184]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid syntax (<string>, line 1)
[2019-06-27 12:49:28,357]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:49:55,316]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:50:57,863]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid syntax (<string>, line 1)
[2019-06-27 12:50:58,052]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:56:34,673]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1} != 200
[2019-06-27 12:56:34,842]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:56:34,844]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:56:55,249]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 12:56:55,251]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:00:18,843]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:00:18,846]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:00:45,455]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:00:45,620]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 13:00:45,661]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:00:57,232]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:00:57,723]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 13:00:57,889]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:01:51,081]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:01:51,230]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:02:30,128]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:02:30,272]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:03:17,733]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:03:17,878]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:04:01,820]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:04:01,992]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:56:33,217]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:56:33,449]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 13:56:33,616]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,358]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,371]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,371]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,371]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,372]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,372]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,373]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,789]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:18,992]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 13:59:19,157]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,158]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,158]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,596]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 13:59:19,596]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,597]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,597]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,597]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,598]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,598]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,598]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,599]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,599]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,599]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:19,600]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:19,600]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:20,339]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 13:59:20,340]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:20,340]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:20,899]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 13:59:20,900]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:20,900]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,305]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 13:59:21,306]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,306]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,306]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,307]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,307]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,307]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,308]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,308]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,308]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,309]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,310]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,310]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,311]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,311]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,311]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,760]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 13:59:21,760]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,760]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,761]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,761]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,762]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,762]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,762]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,763]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,763]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,763]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:21,764]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:21,764]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:22,150]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 13:59:22,150]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:22,150]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:22,667]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 13:59:22,667]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:22,667]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:22,668]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:22,668]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 13:59:22,669]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 13:59:22,669]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,868]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,869]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,870]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,870]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,871]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,871]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:01:48,872]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,897]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,900]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,902]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,903]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,905]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,907]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:05,908]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:55,271]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:55,276]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:55,277]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:55,278]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:02:55,280]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:04:18,199]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:04:18,204]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:04:18,207]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:04:18,209]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:04:18,210]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:05:52,867]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:05:52,871]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:05:52,873]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:05:52,874]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:05:52,875]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:03,477]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:03,764]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:04,071]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:04,393]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:05,203]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,327]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,328]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,328]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,328]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,329]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,329]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:16,330]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,696]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,698]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,700]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,702]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,703]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,704]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:23,705]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:47,160]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:47,433]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:47,782]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:48,086]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:06:48,386]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:32,231]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:32,555]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:32,849]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:33,127]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:33,406]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:33,714]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:34,020]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,079]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,081]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,432]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:07:56,432]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,433]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,434]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,434]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,435]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,436]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,437]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,437]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,438]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,439]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,441]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,442]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:56,871]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:07:56,871]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:56,872]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:57,591]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:07:57,591]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:57,592]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:57,960]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:07:57,961]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:57,962]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:57,965]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:57,965]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:57,967]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:57,967]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:07:57,969]-[ERROR]-log.py-python14-[日志信息]:执行接口失败'dict' object has no attribute 'upper'
[2019-06-27 14:07:57,969]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:17,446]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:17,978]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:08:18,552]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:08:18,552]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 14:08:18,553]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 14:08:18,720]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:19,005]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:19,315]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:19,610]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:19,893]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:20,190]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:20,664]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:08:21,258]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:08:21,258]-[INFO]-log.py-python14-[日志信息]:提现金额0
[2019-06-27 14:08:21,260]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '10256021.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '取现成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '3488999.99',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '取现成功',
 'status': 1}
[2019-06-27 14:08:21,439]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:21,839]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:08:22,456]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:08:22,456]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid literal for int() with base 10: '0.01'
[2019-06-27 14:08:22,645]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:23,237]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:08:23,697]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:08:23,698]-[INFO]-log.py-python14-[日志信息]:提现金额500000
[2019-06-27 14:08:23,698]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14192221.18') != Decimal('14692221.18')
[2019-06-27 14:08:23,865]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:24,181]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:24,467]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:24,757]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:37,561]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:37,983]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 14:08:39,025]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 14:08:39,027]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 14:08:39,029]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 14:08:39,200]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:39,481]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:39,787]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:40,077]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:40,365]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:40,654]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:41,189]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 14:08:41,752]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 14:08:41,753]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 14:08:41,755]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '2989999.98',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 14:08:41,923]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:42,314]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 14:08:43,001]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 14:08:43,002]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 14:08:43,002]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 14:08:43,205]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:43,528]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:43,831]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:54,688]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:08:54,689]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:07,293]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:07,635]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:07,952]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:08,243]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:08,522]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:08,795]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:09,133]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:09,440]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:09,440]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:09,733]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:10,276]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:09:10,831]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:09:10,833]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 14:09:10,834]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 14:09:10,998]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:11,316]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:11,670]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:12,254]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:12,547]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:12,850]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:13,280]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:09:13,859]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:09:13,859]-[INFO]-log.py-python14-[日志信息]:提现金额0
[2019-06-27 14:09:13,860]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是{'sta[36 chars]id': 1123213, 'regname': 'lemonshanshan', 'pwd[158 chars]现成功'} != {'sta[36 chars]id': 88429, 'regname': '小蜜蜂', 'pwd': 'E10ADC39[145 chars]现成功'}
Diff is 766 characters long. Set self.maxDiff to None to see it.
[2019-06-27 14:09:14,031]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:14,547]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:09:15,158]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:09:15,159]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid literal for int() with base 10: '0.01'
[2019-06-27 14:09:15,324]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:15,701]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 14:09:16,310]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 14:09:16,311]-[INFO]-log.py-python14-[日志信息]:提现金额500000
[2019-06-27 14:09:16,311]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14192221.18') != Decimal('14692221.18')
[2019-06-27 14:09:16,478]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:16,806]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:17,127]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:17,412]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:17,718]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:18,015]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:18,423]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:18,729]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:19,029]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:19,350]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:19,657]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 14:09:20,300]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 14:09:20,300]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 14:09:20,301]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 14:09:20,466]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:20,771]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:21,068]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:21,380]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:21,689]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:21,990]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:22,425]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 14:09:23,057]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 14:09:23,058]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 14:09:23,059]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是{'sta[36 chars]id': 1123213, 'regname': 'lemonshanshan', 'pwd[158 chars]值成功'} != {'sta[36 chars]id': 88429, 'regname': '小蜜蜂', 'pwd': 'E10ADC39[145 chars]值成功'}
Diff is 768 characters long. Set self.maxDiff to None to see it.
[2019-06-27 14:09:23,226]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:23,664]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 14:09:24,509]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 14:09:24,510]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 14:09:24,510]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 14:09:24,674]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:24,974]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:09:25,299]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:19:01,979]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:19:02,593]-[INFO]-log.py-python14-[日志信息]:查询到的标id为None
[2019-06-27 14:19:02,761]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:19:02,762]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:21:56,569]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:21:57,292]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:21:57,415]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '更新状态成功：竞标开始，当前标为竞标中状态', 'status': 1} != {'code': '20103', 'data': None, 'msg': '所有参数不能为空', 'status': 0}
[2019-06-27 14:21:57,580]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:23:07,854]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:23:08,572]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:23:08,701]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '更新状态成功：竞标开始，当前标为竞标中状态', 'status': 1} != {'code': '20103', 'data': None, 'msg': '所有参数不能为空', 'status': 0}
[2019-06-27 14:23:08,872]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:24:49,558]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:24:50,443]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:24:50,445]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:25:16,727]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:25:17,521]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:25:17,523]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:27:23,063]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:27:23,763]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:27:23,899]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '更新状态成功：竞标开始，当前标为竞标中状态', 'status': 1} != {'code': '20103', 'data': None, 'msg': '所有参数不能为空', 'status': 0}
[2019-06-27 14:27:24,070]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:28:55,829]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:28:56,607]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:28:58,005]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '更新状态成功：竞标开始，当前标为竞标中状态', 'status': 1} != {'code': '20103', 'data': None, 'msg': '所有参数不能为空', 'status': 0}
[2019-06-27 14:28:58,172]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:30:09,377]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:30:10,164]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:30:10,299]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001', 'data': None, 'msg': '更新状态成功：竞标开始，当前标为竞标中状态', 'status': 1} != {'code': '20103', 'data': None, 'msg': '所有参数不能为空', 'status': 0}
[2019-06-27 14:30:10,477]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:31:16,223]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:31:16,720]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:31:16,724]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:34:22,837]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:34:23,445]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:34:23,447]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:35:02,970]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:35:03,599]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:35:03,600]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:35:31,616]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:35:32,201]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:35:32,206]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:40:28,400]-[ERROR]-log.py-python14-[日志信息]:打开测试用例出错No section: 'GetlistCase'
[2019-06-27 14:40:58,584]-[ERROR]-log.py-python14-[日志信息]:打开测试用例出错No section: 'GetlistCase'
[2019-06-27 14:42:42,597]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:42:42,599]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:42:42,600]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:44:34,076]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:44:34,224]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 14:44:34,394]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:45:31,934]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:45:32,066]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 14:45:32,235]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:46:12,329]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:46:12,480]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 14:46:12,649]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:52:22,484]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:52:22,640]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 14:52:22,821]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:53:38,132]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:53:38,268]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 14:53:38,437]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:54:07,798]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 14:55:35,903]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是eval() arg 1 must be a string, bytes or code object
[2019-06-27 14:55:35,963]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:05,162]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:06,540]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:07,681]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:08,971]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:10,326]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:11,356]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:12,496]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:13,757]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:39,710]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:40,340]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:02:40,342]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:03:50,409]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:03:51,477]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:03:51,479]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:05,053]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:05,330]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:05,611]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:05,895]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:06,206]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:06,531]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:06,842]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:07,138]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:24,675]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:24,975]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:25,261]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:25,539]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:25,841]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:26,152]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:26,480]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:31,771]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:32,221]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:04:32,881]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:04:32,882]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 15:04:32,882]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 15:04:33,054]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:33,344]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:33,649]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:33,942]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:34,237]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:34,661]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:35,113]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:04:35,778]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:04:35,780]-[INFO]-log.py-python14-[日志信息]:提现金额0
[2019-06-27 15:04:35,783]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '10256021.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '取现成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '3470999.97',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '取现成功',
 'status': 1}
[2019-06-27 15:04:35,978]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:36,384]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:04:37,182]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:04:37,183]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid literal for int() with base 10: '0.01'
[2019-06-27 15:04:37,350]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:38,118]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:04:38,825]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:04:38,826]-[INFO]-log.py-python14-[日志信息]:提现金额500000
[2019-06-27 15:04:38,826]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14192221.18') != Decimal('14692221.18')
[2019-06-27 15:04:38,995]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:39,292]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:40,413]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:40,705]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:46,205]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:46,499]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:46,809]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:47,123]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:47,458]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:51,411]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:51,938]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:04:52,621]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:04:52,621]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 15:04:52,621]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 15:04:52,792]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:53,084]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:53,371]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:53,653]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:53,941]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:54,254]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:54,910]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:04:55,470]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:04:55,470]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 15:04:55,472]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: {'code': '10001',
 'data': {'id': 1123213,
          'leaveamount': '14692221.18',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': 'lemonshanshan',
          'regtime': '2019-03-09 13:08:54.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1} != {'code': '10001',
 'data': {'id': 88429,
          'leaveamount': '2971999.96',
          'mobilephone': '15382876192',
          'pwd': 'E10ADC3949BA59ABBE56E057F20F883E',
          'regname': '小蜜蜂',
          'regtime': '2019-06-26 14:49:46.0',
          'type': '1'},
 'msg': '充值成功',
 'status': 1}
[2019-06-27 15:04:55,668]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:56,070]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:04:56,702]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:04:56,703]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 15:04:56,703]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是 :: Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 15:04:56,875]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:57,175]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:04:57,449]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:02,291]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:02,898]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:03,186]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:03,534]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:03,853]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:04,207]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:04,493]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:26,113]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:26,724]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:27,012]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:27,308]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:27,614]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:27,922]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:28,303]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:28,650]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:29,117]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:05:29,750]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:05:29,751]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 15:05:29,751]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 15:05:29,919]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:30,250]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:30,572]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:30,929]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:31,222]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:31,531]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:31,915]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:05:32,480]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:05:32,481]-[INFO]-log.py-python14-[日志信息]:提现金额0
[2019-06-27 15:05:32,482]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是{'sta[36 chars]id': 1123213, 'regname': 'lemonshanshan', 'pwd[158 chars]现成功'} != {'sta[36 chars]id': 88429, 'regname': '小蜜蜂', 'pwd': 'E10ADC39[145 chars]现成功'}
Diff is 767 characters long. Set self.maxDiff to None to see it.
[2019-06-27 15:05:32,651]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:33,026]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:05:33,700]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:05:33,702]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid literal for int() with base 10: '0.01'
[2019-06-27 15:05:33,871]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:34,338]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:05:34,901]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:05:34,903]-[INFO]-log.py-python14-[日志信息]:提现金额500000
[2019-06-27 15:05:34,904]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14192221.18') != Decimal('14692221.18')
[2019-06-27 15:05:35,083]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:35,393]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:35,696]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:36,053]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:36,362]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:36,653]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:36,958]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:37,255]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:37,544]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:37,839]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:38,218]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:05:39,378]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:05:39,379]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 15:05:39,379]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 15:05:39,570]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:39,863]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:40,157]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:40,460]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:40,763]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:41,090]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:41,539]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:05:42,066]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:05:42,066]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 15:05:42,068]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是{'sta[36 chars]id': 1123213, 'regname': 'lemonshanshan', 'pwd[158 chars]值成功'} != {'sta[36 chars]id': 88429, 'regname': '小蜜蜂', 'pwd': 'E10ADC39[145 chars]值成功'}
Diff is 768 characters long. Set self.maxDiff to None to see it.
[2019-06-27 15:05:42,237]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:42,630]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:05:43,186]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:05:43,187]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 15:05:43,187]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 15:05:43,354]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:43,818]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:44,107]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:44,431]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:45,031]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:05:45,032]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:03,299]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:04,329]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:04,626]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:04,933]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:05,239]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:05,543]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:05,828]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:06,119]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:06,748]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:26:07,394]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:26:07,395]-[INFO]-log.py-python14-[日志信息]:提现金额10000
[2019-06-27 15:26:07,395]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14682221.18') != Decimal('14692221.18')
[2019-06-27 15:26:07,565]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:07,886]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:08,176]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:08,472]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:08,759]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:09,055]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:09,401]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:26:10,081]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:26:10,082]-[INFO]-log.py-python14-[日志信息]:提现金额0
[2019-06-27 15:26:10,083]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是{'sta[36 chars]id': 1123213, 'regname': 'lemonshanshan', 'pwd[158 chars]现成功'} != {'sta[36 chars]id': 88429, 'regname': '小蜜蜂', 'pwd': 'E10ADC39[145 chars]现成功'}
Diff is 767 characters long. Set self.maxDiff to None to see it.
[2019-06-27 15:26:10,250]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:10,651]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:26:11,290]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:26:11,290]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是invalid literal for int() with base 10: '0.01'
[2019-06-27 15:26:11,458]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:11,929]-[INFO]-log.py-python14-[日志信息]:提现之前的金额为14692221.18
[2019-06-27 15:26:12,563]-[INFO]-log.py-python14-[日志信息]:提现之后的金额为14692221.18
[2019-06-27 15:26:12,563]-[INFO]-log.py-python14-[日志信息]:提现金额500000
[2019-06-27 15:26:12,563]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14192221.18') != Decimal('14692221.18')
[2019-06-27 15:26:12,747]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:13,072]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:13,384]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:13,740]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:14,058]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:14,374]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:14,694]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:15,741]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:16,035]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:16,343]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:16,730]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:26:17,453]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:26:17,454]-[INFO]-log.py-python14-[日志信息]:充值金额1000
[2019-06-27 15:26:17,454]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('14693221.18') != Decimal('14692221.18')
[2019-06-27 15:26:17,646]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:17,993]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:18,303]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:18,592]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:18,902]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:19,193]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:19,596]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:26:20,274]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:26:20,274]-[INFO]-log.py-python14-[日志信息]:充值金额0
[2019-06-27 15:26:20,275]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是{'sta[36 chars]id': 1123213, 'regname': 'lemonshanshan', 'pwd[158 chars]值成功'} != {'sta[36 chars]id': 88429, 'regname': '小蜜蜂', 'pwd': 'E10ADC39[145 chars]值成功'}
Diff is 767 characters long. Set self.maxDiff to None to see it.
[2019-06-27 15:26:20,451]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:20,889]-[INFO]-log.py-python14-[日志信息]:充值之前的金额为14692221.18
[2019-06-27 15:26:21,517]-[INFO]-log.py-python14-[日志信息]:充值之后的金额为14692221.18
[2019-06-27 15:26:21,517]-[INFO]-log.py-python14-[日志信息]:充值金额500000
[2019-06-27 15:26:21,518]-[ERROR]-log.py-python14-[日志信息]:执行接口测试出错,错误是Decimal('15192221.18') != Decimal('14692221.18')
[2019-06-27 15:26:21,686]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:22,016]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:22,358]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:22,748]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:23,445]-[INFO]-log.py-python14-[日志信息]:结束测试!
[2019-06-27 15:26:23,447]-[INFO]-log.py-python14-[日志信息]:结束测试!
